sudo: true
os: osx 
cache: false
language: node_js
node_js: "8"

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
# delete the following line before encrypting your server.key
- openssl aes-256-cbc -K $encrypted_ddb2fdebbf95_key -iv $encrypted_ddb2fdebbf95_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
#- mkdir sfdx
#- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
#- "./sfdx/install"
#- export PATH=./sfdx/$(pwd):$PATH
- npm i -g sfdx-cli
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human --wait 10 && sfdx force:org:delete -u ciorg -p